[package]
name = "ruxen"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
description = "Rust port of nginx, Linux-only, HTTP/1.1, no modules, no cache"
repository = "https://github.com/gvozdetsky/ruxen"
authors = ["Eugene Gvozdetsky <gvozdet@gmail.com>"]

[dependencies]
bytes = "1"
libc = "0.2"
monoio = "0.2.4"
regex = "1"
rustls = "0.23"
rustls-pemfile = "2"

[dev-dependencies]
rcgen = "0.14"
